[package]
name = "gane_driver"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
clap = { workspace = true }
colored = { workspace = true }
gane_diagnostics = { path = "../diagnostics" }
gane_codegen = { path = "../codegen" }
gane_ir = { path = "../ir" }
gane_parser = { path= "../parser" }
gane_sema = { path = "../sema" }
gane_interpreter = { path = "../interpreter" }
